import type { DashboardResponse } from "@/types/api";

export const mockDashboardResponse: DashboardResponse = {
  success: true,
  counts: {
    _id: null,
    total: 120,
    male: 68,
    female: 52,
    pending: 19,
  },
  recentVerified: [
    {
      _id: "profile_1",
      tenantId: "tenant_main",
      name: "Ananya Sharma",
      gender: "female",
      dob: "1995-06-12",
      height: { raw: `5'5"`, value: 165 },
      weight: { raw: "60 kg", value: 60 },
      maritalStatus: "Never Married",
      religion: "Hindu",
      caste: "Brahmin",
      subCaste: "Saraswat",
      gotra: "Bhargava",
      motherTongue: "Hindi",
      languagesKnown: ["Hindi", "English"],
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
      education: "MBA",
      jobTitle: "Product Manager",
      designation: "Senior PM",
      sector: "Technology",
      jobDescription: "Leading product strategy for a fintech platform.",
      income: { raw: "₹24 LPA", value: 2400000 },
      plansAbroad: "Open to relocation",
      familyType: "Nuclear",
      familyValues: "Traditional",
      familyIncome: { raw: "₹35 LPA", value: 3500000 },
      fatherOccupation: "Businessman",
      motherOccupation: "Educator",
      siblingsCount: 1,
      mobile: "+91-9000000001",
      secondaryMobile: "+91-9000000002",
      email: "ananya.sharma@example.com",
      horoscope: {
        rashi: "Mithun",
        nakshatra: "Punarvasu",
        naadi: "Adi",
        manglik: "No",
        doshas: [],
        kundliMatchRequired: true,
        placeOfBirth: "Mumbai",
        timeOfBirth: { hour: 5, minute: 45, ampm: "AM" },
      },
      lifestyle: {
        diet: "Vegetarian",
        drinking: "Never",
        smoking: "Never",
        hobbies: ["Traveling", "Painting"],
        interests: ["Yoga", "Classical Music"],
      },
      assets: {
        ownsHouse: true,
        ownsCar: true,
        otherAssets: ["Mutual Funds"],
      },
      preferredAge: { min: 28, max: 34 },
      preferredHeight: { min: 160, max: 180 },
      preferredReligion: ["Hindu"],
      preferredCaste: ["Brahmin"],
      preferredSubCaste: ["Saraswat"],
      preferredEducation: ["MBA", "BTech"],
      preferredLocation: ["Mumbai", "Pune", "Bengaluru"],
      preferredLifestyle: { diet: "Vegetarian", drinking: "Never", smoking: "Never" },
      mediaFiles: [
        "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=960&q=60",
        "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=960&q=60",
        "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=960&q=60",
      ],
      status: "verified",
      profileCompletePercentage: 92,
      lastUpdated: "2024-04-15T06:30:00.000Z",
      createdAt: "2023-12-10T09:15:00.000Z",
      updatedAt: "2024-04-15T06:30:00.000Z",
      __v: 0,
    },
    {
      _id: "profile_2",
      tenantId: "tenant_main",
      name: "Rahul Verma",
      gender: "male",
      dob: "1990-11-05",
      height: { raw: `5'10"`, value: 178 },
      weight: { raw: "75 kg", value: 75 },
      maritalStatus: "Never Married",
      religion: "Hindu",
      caste: "Kayastha",
      subCaste: "Srivastava",
      gotra: "Kashyap",
      motherTongue: "Hindi",
      languagesKnown: ["Hindi", "English"],
      city: "Delhi",
      state: "Delhi",
      country: "India",
      education: "B.Tech",
      jobTitle: "Solutions Architect",
      designation: "Principal Architect",
      sector: "Information Technology",
      jobDescription: "Designing scalable cloud-native enterprise platforms.",
      income: { raw: "₹32 LPA", value: 3200000 },
      plansAbroad: "Considering within 2 years",
      familyType: "Joint",
      familyValues: "Moderate",
      familyIncome: { raw: "₹42 LPA", value: 4200000 },
      fatherOccupation: "Government Officer",
      motherOccupation: "Homemaker",
      siblingsCount: 2,
      mobile: "+91-9000000003",
      secondaryMobile: "+91-9000000004",
      email: "rahul.verma@example.com",
      horoscope: {
        rashi: "Dhanu",
        nakshatra: "Moola",
        naadi: "Adi",
        manglik: "No",
        doshas: ["Kaal Sarpa"],
        kundliMatchRequired: true,
        placeOfBirth: "Delhi",
        timeOfBirth: { hour: 3, minute: 10, ampm: "AM" },
      },
      lifestyle: {
        diet: "Eggetarian",
        drinking: "Occasionally",
        smoking: "Never",
        hobbies: ["Cycling", "Guitar"],
        interests: ["Startups", "Meditation"],
      },
      assets: {
        ownsHouse: true,
        ownsCar: true,
        otherAssets: ["Stocks", "Cryptocurrency"],
      },
      preferredAge: { min: 24, max: 32 },
      preferredHeight: { min: 155, max: 175 },
      preferredReligion: ["Hindu"],
      preferredCaste: ["Hindu"],
      preferredSubCaste: [],
      preferredEducation: ["MBA", "M.Tech"],
      preferredLocation: ["Delhi", "Gurgaon", "Noida"],
      preferredLifestyle: { diet: "Vegetarian", drinking: "Occasionally", smoking: "Never" },
      mediaFiles: [
        "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=960&q=60",
        "https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=960&q=60",
        "https://images.unsplash.com/photo-1519340241574-2cec6aef0c01?auto=format&fit=crop&w=960&q=60",
      ],
      status: "verified",
      profileCompletePercentage: 88,
      lastUpdated: "2024-04-12T12:10:00.000Z",
      createdAt: "2023-11-22T08:40:00.000Z",
      updatedAt: "2024-04-12T12:10:00.000Z",
      __v: 0,
    },
  ],
  recentPending: [
    {
      _id: "pending_1",
      tenantId: "tenant_main",
      name: "Rohan Mehta",
      gender: "male",
      languagesKnown: ["Hindi", "English"],
      mobile: "+91-9000000010",
      horoscope: { doshas: ["Manglik"] },
      lifestyle: {
        hobbies: ["Cycling", "Music"],
        interests: ["Photography", "Technology"],
      },
      assets: { otherAssets: ["Family Business", "Commercial Property"] },
      preferredReligion: ["Hindu"],
      preferredCaste: ["Vaishya"],
      preferredSubCaste: [],
      preferredEducation: ["MBA", "CA"],
      preferredLocation: ["Delhi", "Gurgaon"],
      mediaFiles: [
        "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=960&q=60",
        "https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?auto=format&fit=crop&w=960&q=60",
      ],
      status: "pending",
      profileCompletePercentage: 68,
      lastUpdated: "2024-04-10T05:25:00.000Z",
      createdAt: "2024-04-08T09:00:00.000Z",
      updatedAt: "2024-04-10T05:25:00.000Z",
      __v: 0,
    },
    {
      _id: "pending_2",
      tenantId: "tenant_main",
      name: "Sanya Iyer",
      gender: "female",
      languagesKnown: ["Kannada", "English"],
      mobile: "+91-9000000011",
      horoscope: { doshas: [] },
      lifestyle: {
        hobbies: ["Classical Dance", "Sketching"],
        interests: ["Wellness Retreats", "Volunteering"],
      },
      assets: { otherAssets: ["Gold", "Mutual Funds"] },
      preferredReligion: ["Hindu"],
      preferredCaste: ["Iyer"],
      preferredSubCaste: ["Vadama"],
      preferredEducation: ["MBA", "MS"],
      preferredLocation: ["Bengaluru", "Chennai"],
      mediaFiles: [
        "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=960&q=60",
        "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=960&q=60",
      ],
      status: "pending",
      profileCompletePercentage: 75,
      lastUpdated: "2024-04-11T07:45:00.000Z",
      createdAt: "2024-04-09T14:20:00.000Z",
      updatedAt: "2024-04-11T07:45:00.000Z",
      __v: 0,
    },
  ],
};