export const mockProfiles = [
  {
    id: "1",
    name: "Rajesh Kumar",
    email: "rajesh.kumar@email.com",
    phone: "+91 98765 43210",
    age: 28,
    gender: "male",
    religion: "Hindu",
    caste: "Brahmin",
    education: "B.Tech Computer Science",
    occupation: "Software Engineer",
    income: "₹12 LPA",
    height: "5'10\"",
    maritalStatus: "single",
    city: "Bangalore",
    state: "Karnataka",
    fatherName: "Suresh Kumar",
    motherName: "Lakshmi Kumar",
    siblings: "1 Sister",
    expectations: "Looking for educated, family-oriented partner",
    photos: [
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=960&q=60",
      "https://images.unsplash.com/photo-1607746882042-944635dfe10e?auto=format&fit=crop&w=960&q=60",
      "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=960&q=60",
    ],
    verified: true,
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    name: "Priya Sharma",
    email: "priya.sharma@email.com",
    phone: "+91 98765 43211",
    age: 26,
    gender: "female",
    religion: "Hindu",
    caste: "Rajput",
    education: "MBA Finance",
    occupation: "Financial Analyst",
    income: "₹10 LPA",
    height: "5'5\"",
    maritalStatus: "single",
    city: "Mumbai",
    state: "Maharashtra",
    fatherName: "Vikram Sharma",
    motherName: "Anjali Sharma",
    siblings: "1 Brother",
    expectations: "Seeking well-settled professional",
    photos: [
      "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=960&q=60",
      "https://images.unsplash.com/photo-1502389614483-e475fc34407e?auto=format&fit=crop&w=960&q=60",
      "https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?auto=format&fit=crop&w=960&q=60",
    ],
    verified: true,
    createdAt: "2024-01-18",
  },
  {
    id: "3",
    name: "Amit Patel",
    email: "amit.patel@email.com",
    phone: "+91 98765 43212",
    age: 32,
    gender: "male",
    religion: "Hindu",
    caste: "Patel",
    education: "CA (Chartered Accountant)",
    occupation: "Senior Accountant",
    income: "₹15 LPA",
    height: "5'8\"",
    maritalStatus: "single",
    city: "Ahmedabad",
    state: "Gujarat",
    fatherName: "Ramesh Patel",
    motherName: "Meera Patel",
    siblings: "2 Sisters",
    expectations: "Looking for traditional family values",
    photos: [
      "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=960&q=60",
      "https://images.unsplash.com/photo-1607746882042-944635dfe10e?auto=format&fit=crop&w=960&q=60"
    ],
    verified: false,
    createdAt: "2024-01-20",
  },
  {
    id: "4",
    name: "Sneha Reddy",
    email: "sneha.reddy@email.com",
    phone: "+91 98765 43213",
    age: 25,
    gender: "female",
    religion: "Hindu",
    caste: "Reddy",
    education: "MBBS",
    occupation: "Doctor",
    income: "₹18 LPA",
    height: "5'6\"",
    maritalStatus: "single",
    city: "Hyderabad",
    state: "Telangana",
    fatherName: "Krishna Reddy",
    motherName: "Saroja Reddy",
    siblings: "None",
    expectations: "Prefer medical professional or engineer",
    photos: [
      "https://images.unsplash.com/photo-1520974722075-364e4ea66ee8?auto=format&fit=crop&w=960&q=60",
      "https://images.unsplash.com/photo-1542596768-5d1d21f1cf98?auto=format&fit=crop&w=960&q=60",
    ],
    verified: true,
    createdAt: "2024-01-22",
  },
  {
    id: "5",
    name: "Arjun Singh",
    email: "arjun.singh@email.com",
    phone: "+91 98765 43214",
    age: 30,
    gender: "male",
    religion: "Sikh",
    caste: "Jat",
    education: "B.Com",
    occupation: "Business Owner",
    income: "₹20 LPA",
    height: "6'0\"",
    maritalStatus: "single",
    city: "Delhi",
    state: "Delhi",
    fatherName: "Harjeet Singh",
    motherName: "Kulwinder Kaur",
    siblings: "1 Brother, 1 Sister",
    expectations: "Looking for understanding life partner",
    photos: [
      "https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=960&q=60",
      "https://images.unsplash.com/photo-1519340241574-2cec6aef0c01?auto=format&fit=crop&w=960&q=60",
    ],
    verified: false,
    createdAt: "2024-01-25",
  },
  {
    id: "6",
    name: "Kavya Iyer",
    email: "kavya.iyer@email.com",
    phone: "+91 98765 43215",
    age: 27,
    gender: "female",
    religion: "Hindu",
    caste: "Iyer",
    education: "M.Sc Physics",
    occupation: "Research Scientist",
    income: "₹9 LPA",
    height: "5'4\"",
    maritalStatus: "single",
    city: "Chennai",
    state: "Tamil Nadu",
    fatherName: "Venkatesh Iyer",
    motherName: "Radha Iyer",
    siblings: "1 Sister",
    expectations: "Seeking educated and cultured family",
    photos: [
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=960&q=60",
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=960&q=60"
    ],
    verified: true,
    createdAt: "2024-01-28",
  },
  {
    id: "7",
    name: "Rahul Verma",
    email: "rahul.verma@email.com",
    phone: "+91 98765 43216",
    age: 29,
    gender: "male",
    religion: "Hindu",
    caste: "Kayastha",
    education: "B.E Mechanical",
    occupation: "Project Manager",
    income: "₹14 LPA",
    height: "5'9\"",
    maritalStatus: "divorced",
    city: "Pune",
    state: "Maharashtra",
    fatherName: "Ashok Verma",
    motherName: "Sunita Verma",
    siblings: "1 Brother",
    expectations: "Looking for second chance at happiness",
    photos: [
      "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=960&q=60",
      "https://images.unsplash.com/photo-1519340241574-2cec6aef0c01?auto=format&fit=crop&w=960&q=60"
    ],
    verified: true,
    createdAt: "2024-02-01",
  },
  {
    id: "8",
    name: "Ananya Das",
    email: "ananya.das@email.com",
    phone: "+91 98765 43217",
    age: 24,
    gender: "female",
    religion: "Hindu",
    caste: "Bengali",
    education: "B.A English Literature",
    occupation: "Content Writer",
    income: "₹6 LPA",
    height: "5'3\"",
    maritalStatus: "single",
    city: "Kolkata",
    state: "West Bengal",
    fatherName: "Subhash Das",
    motherName: "Mita Das",
    siblings: "None",
    expectations: "Looking for creative and supportive partner",
    photos: [
      "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=960&q=60",
      "https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?auto=format&fit=crop&w=960&q=60"
    ],
    verified: false,
    createdAt: "2024-02-03",
  },
  {
    id: "9",
    name: "Vikram Malhotra",
    email: "vikram.malhotra@email.com",
    phone: "+91 98765 43218",
    age: 31,
    gender: "male",
    religion: "Hindu",
    caste: "Khatri",
    education: "B.Tech Electronics",
    occupation: "Hardware Engineer",
    income: "₹16 LPA",
    height: "5'11\"",
    maritalStatus: "single",
    city: "Chandigarh",
    state: "Punjab",
    fatherName: "Rajiv Malhotra",
    motherName: "Neeta Malhotra",
    siblings: "1 Sister",
    expectations: "Seeking career-oriented partner",
    verified: true,
    createdAt: "2024-02-05",
  },
  {
    id: "10",
    name: "Divya Nair",
    email: "divya.nair@email.com",
    phone: "+91 98765 43219",
    age: 26,
    gender: "female",
    religion: "Hindu",
    caste: "Nair",
    education: "B.Sc Nursing",
    occupation: "Nurse",
    income: "₹7 LPA",
    height: "5'5\"",
    maritalStatus: "single",
    city: "Kochi",
    state: "Kerala",
    fatherName: "Suresh Nair",
    motherName: "Latha Nair",
    siblings: "1 Brother",
    expectations: "Looking for caring and responsible partner",
    verified: true,
    createdAt: "2024-02-08",
  },
  {
    id: "11",
    name: "Karan Chopra",
    email: "karan.chopra@email.com",
    phone: "+91 98765 43220",
    age: 33,
    gender: "male",
    religion: "Hindu",
    caste: "Arora",
    education: "MBA Marketing",
    occupation: "Marketing Manager",
    income: "₹18 LPA",
    height: "6'1\"",
    maritalStatus: "single",
    city: "Gurgaon",
    state: "Haryana",
    fatherName: "Anil Chopra",
    motherName: "Ritu Chopra",
    siblings: "None",
    expectations: "Seeking independent and modern partner",
    photos: [
      "https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=960&q=60",
      "https://images.unsplash.com/photo-1607746882042-944635dfe10e?auto=format&fit=crop&w=960&q=60"
    ],
    verified: false,
    createdAt: "2024-02-10",
  },
  {
    id: "12",
    name: "Meera Joshi",
    email: "meera.joshi@email.com",
    phone: "+91 98765 43221",
    age: 28,
    gender: "female",
    religion: "Hindu",
    caste: "Brahmin",
    education: "M.A Psychology",
    occupation: "Clinical Psychologist",
    income: "₹11 LPA",
    height: "5'4\"",
    maritalStatus: "single",
    city: "Jaipur",
    state: "Rajasthan",
    fatherName: "Prakash Joshi",
    motherName: "Kavita Joshi",
    siblings: "2 Brothers",
    expectations: "Looking for emotionally mature partner",
    verified: true,
    createdAt: "2024-02-12",
  },
  {
    id: "13",
    name: "Aditya Gupta",
    email: "aditya.gupta@email.com",
    phone: "+91 98765 43222",
    age: 27,
    gender: "male",
    religion: "Hindu",
    caste: "Agarwal",
    education: "B.Com + CA",
    occupation: "Chartered Accountant",
    income: "₹13 LPA",
    height: "5'10\"",
    maritalStatus: "single",
    city: "Indore",
    state: "Madhya Pradesh",
    fatherName: "Mahesh Gupta",
    motherName: "Suman Gupta",
    siblings: "1 Sister",
    expectations: "Prefer traditional family background",
    verified: true,
    createdAt: "2024-02-15",
  },
  {
    id: "14",
    name: "Pooja Desai",
    email: "pooja.desai@email.com",
    phone: "+91 98765 43223",
    age: 25,
    gender: "female",
    religion: "Hindu",
    caste: "Patel",
    education: "B.Pharm",
    occupation: "Pharmacist",
    income: "₹8 LPA",
    height: "5'3\"",
    maritalStatus: "single",
    city: "Surat",
    state: "Gujarat",
    fatherName: "Jayesh Desai",
    motherName: "Hetal Desai",
    siblings: "1 Brother",
    expectations: "Looking for well-educated partner",
    verified: false,
    createdAt: "2024-02-18",
  },
  {
    id: "15",
    name: "Rohan Kapoor",
    email: "rohan.kapoor@email.com",
    phone: "+91 98765 43224",
    age: 29,
    gender: "male",
    religion: "Hindu",
    caste: "Punjabi",
    education: "B.Tech Civil",
    occupation: "Civil Engineer",
    income: "₹12 LPA",
    height: "5'9\"",
    maritalStatus: "single",
    city: "Ludhiana",
    state: "Punjab",
    fatherName: "Sunil Kapoor",
    motherName: "Preeti Kapoor",
    siblings: "1 Brother, 1 Sister",
    expectations: "Seeking family-oriented partner",
    verified: true,
    createdAt: "2024-02-20",
  },
  {
    id: "16",
    name: "Nisha Pillai",
    email: "nisha.pillai@email.com",
    phone: "+91 98765 43225",
    age: 27,
    gender: "female",
    religion: "Hindu",
    caste: "Nair",
    education: "B.Tech IT",
    occupation: "Software Developer",
    income: "₹14 LPA",
    height: "5'6\"",
    maritalStatus: "single",
    city: "Trivandrum",
    state: "Kerala",
    fatherName: "Rajan Pillai",
    motherName: "Maya Pillai",
    siblings: "None",
    expectations: "Looking for tech-savvy partner",
    verified: true,
    createdAt: "2024-02-22",
  },
  {
    id: "17",
    name: "Sanjay Rao",
    email: "sanjay.rao@email.com",
    phone: "+91 98765 43226",
    age: 34,
    gender: "male",
    religion: "Hindu",
    caste: "Reddy",
    education: "M.Tech Mechanical",
    occupation: "Senior Engineer",
    income: "₹19 LPA",
    height: "5'11\"",
    maritalStatus: "divorced",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    fatherName: "Venkat Rao",
    motherName: "Lakshmi Rao",
    siblings: "1 Sister",
    expectations: "Looking for understanding partner",
    verified: false,
    createdAt: "2024-02-25",
  },
  {
    id: "18",
    name: "Riya Banerjee",
    email: "riya.banerjee@email.com",
    phone: "+91 98765 43227",
    age: 26,
    gender: "female",
    religion: "Hindu",
    caste: "Bengali",
    education: "M.A Economics",
    occupation: "Economist",
    income: "₹10 LPA",
    height: "5'4\"",
    maritalStatus: "single",
    city: "Kolkata",
    state: "West Bengal",
    fatherName: "Amit Banerjee",
    motherName: "Rina Banerjee",
    siblings: "1 Brother",
    expectations: "Seeking intellectually compatible partner",
    verified: true,
    createdAt: "2024-02-28",
  },
  {
    id: "19",
    name: "Manish Agarwal",
    email: "manish.agarwal@email.com",
    phone: "+91 98765 43228",
    age: 30,
    gender: "male",
    religion: "Hindu",
    caste: "Marwari",
    education: "B.Com",
    occupation: "Business Owner",
    income: "₹25 LPA",
    height: "5'8\"",
    maritalStatus: "single",
    city: "Jaipur",
    state: "Rajasthan",
    fatherName: "Ramesh Agarwal",
    motherName: "Sunita Agarwal",
    siblings: "2 Brothers",
    expectations: "Looking for business-minded family",
    verified: true,
    createdAt: "2024-03-02",
  },
  {
    id: "20",
    name: "Tanvi Shah",
    email: "tanvi.shah@email.com",
    phone: "+91 98765 43229",
    age: 24,
    gender: "female",
    religion: "Hindu",
    caste: "Gujarati",
    education: "B.Des Fashion",
    occupation: "Fashion Designer",
    income: "₹9 LPA",
    height: "5'5\"",
    maritalStatus: "single",
    city: "Mumbai",
    state: "Maharashtra",
    fatherName: "Kiran Shah",
    motherName: "Nisha Shah",
    siblings: "1 Sister",
    expectations: "Seeking creative and supportive partner",
    verified: false,
    createdAt: "2024-03-05",
  },
];

const SAMPLE_PHOTOS: Array<string> = [
  "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=960&q=60",
  "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=960&q=60",
  "https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=960&q=60",
  "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=960&q=60",
  "https://images.unsplash.com/photo-1519340241574-2cec6aef0c01?auto=format&fit=crop&w=960&q=60",
];

for (const p of mockProfiles as Array<Record<string, any>>) {
  const existing: Array<string> = Array.isArray(p.photos)
    ? (p.photos as Array<string | null | undefined>).filter((u): u is string => typeof u === "string" && u.trim().length > 0)
    : [];
  const filled: Array<string> = [...existing];
  let i = 0;
  while (filled.length < 5) {
    filled.push(SAMPLE_PHOTOS[i % SAMPLE_PHOTOS.length]);
    i++;
  }
  p.photos = filled.slice(0, 5);
}

export const MOCK_CITIES = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Pune",
  "Ahmedabad",
  "Jaipur",
  "Lucknow",
  "Chandigarh",
  "Indore",
  "Nagpur",
  "Visakhapatnam",
  "Coimbatore",
];

export const MOCK_EDUCATION_LEVELS = [
  "High School",
  "Diploma",
  "Bachelor's Degree",
  "B.Tech/B.E.",
  "B.Com",
  "B.Sc",
  "B.A",
  "Master's Degree",
  "M.Tech/M.E.",
  "MBA",
  "M.Com",
  "M.Sc",
  "M.A",
  "PhD",
  "Medical Degree (MBBS/MD)",
  "Law Degree (LLB/LLM)",
];

export const MOCK_PROFESSIONS = [
  "Software Engineer",
  "Doctor",
  "Teacher",
  "Business Owner",
  "Accountant",
  "Lawyer",
  "Engineer",
  "Nurse",
  "Architect",
  "Consultant",
  "Government Employee",
  "Private Employee",
  "Self Employed",
  "Student",
  "Homemaker",
  "Other",
];

export const MOCK_CASTES = [
  "Brahmin",
  "Kshatriya",
  "Vaishya",
  "Shudra",
  "Reddy",
  "Kamma",
  "Kapu",
  "Velama",
  "Naidu",
  "Gowda",
  "Nair",
  "Ezhava",
  "Jat",
  "Rajput",
  "Other",
];

export const MOCK_RELIGIONS = [
  "Hindu",
  "Muslim",
  "Christian",
  "Sikh",
  "Buddhist",
  "Jain",
  "Other",
];

export const MOCK_MARITAL_STATUS = [
  "single",
  "divorced",
  "widowed",
];

export const MOCK_MOTHER_TONGUES = [
  "Telugu",
  "Hindi",
  "Tamil",
  "Kannada",
  "Malayalam",
  "Marathi",
  "Bengali",
  "Gujarati",
  "Punjabi",
  "English",
  "Other",
];

export const MOCK_NADIS = [
  "Aadi",
  "Madhya",
  "Antya",
];

export const MOCK_GOTHRAS = [
  "Bharadwaja",
  "Kashyapa",
  "Vashishta",
  "Vishwamitra",
  "Atri",
  "Jamadagni",
  "Gautama",
  "Other",
];

export const MOCK_FAMILY_TYPES = [
  "Nuclear",
  "Joint",
];

export const MOCK_FOOD_HABITS = [
  "Vegetarian",
  "Non-Vegetarian",
  "Eggetarian",
];

export const MOCK_DRINKING_HABITS = [
  "Never",
  "Occasionally",
  "Regularly",
];

export const MOCK_SMOKING_HABITS = [
  "Never",
  "Occasionally",
  "Regularly",
];

export const MOCK_HOBBIES = [
  "Reading",
  "Traveling",
  "Cooking",
  "Music",
  "Sports",
  "Photography",
  "Dancing",
  "Painting",
  "Gardening",
  "Yoga",
];

export const MOCK_STATES = [
  "Andhra Pradesh",
  "Telangana",
  "Karnataka",
  "Tamil Nadu",
  "Kerala",
  "Maharashtra",
  "Gujarat",
  "Rajasthan",
  "Delhi",
  "Punjab",
  "Haryana",
  "Uttar Pradesh",
  "West Bengal",
  "Madhya Pradesh",
  "Other",
];